# -*- coding: utf-8 -*-
"""training-siamese-network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ldD6nmG8z6QOJZ_b1aLGBM2810rvvqs
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
from PIL import Image
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
import os

# Define the device (GPU or CPU)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Define Siamese Network class (same as you had)
class SiameseNetwork(nn.Module):
    def __init__(self):
        super(SiameseNetwork, self).__init__()
        self.cnn1 = nn.Sequential(
            nn.Conv2d(1, 96, kernel_size=11, stride=1),
            nn.ReLU(inplace=True),
            nn.LocalResponseNorm(5, alpha=0.0001, beta=0.75, k=2),
            nn.MaxPool2d(3, stride=2),

            nn.Conv2d(96, 256, kernel_size=5, stride=1, padding=2),
            nn.ReLU(inplace=True),
            nn.LocalResponseNorm(5, alpha=0.0001, beta=0.75, k=2),
            nn.MaxPool2d(3, stride=2),
            nn.Dropout2d(p=0.3),

            nn.Conv2d(256, 384, kernel_size=3, stride=1, padding=1),
            nn.ReLU(inplace=True),

            nn.Conv2d(384, 256, kernel_size=3, stride=1, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(3, stride=2),
            nn.Dropout2d(p=0.3),
        )

        self.fc1 = nn.Sequential(
            nn.Linear(25600, 1024),
            nn.ReLU(inplace=True),
            nn.Dropout2d(p=0.5),

            nn.Linear(1024, 128),
            nn.ReLU(inplace=True),

            nn.Linear(128, 2)
        )

    def forward_once(self, x):
        output = self.cnn1(x)
        output = output.view(output.size()[0], -1)
        output = self.fc1(output)
        return output

    def forward(self, input1, input2):
        output1 = self.forward_once(input1)
        output2 = self.forward_once(input2)
        return output1, output2

# Define the Contrastive Loss class
class ContrastiveLoss(nn.Module):
    def __init__(self, margin=2.0):
        super(ContrastiveLoss, self).__init__()
        self.margin = margin

    def forward(self, output1, output2, label):
        euclidean_distance = F.pairwise_distance(output1, output2, keepdim=True)
        loss_contrastive = torch.mean((1 - label) * torch.pow(euclidean_distance, 2) +
                                      (label) * torch.pow(torch.clamp(self.margin - euclidean_distance, min=0.0), 2))
        return loss_contrastive

# Prepare the dataset (same as your existing code)
class SiameseData(Dataset):
    def __init__(self, train_csv=None, train_dir=None, transform=None):
        self.train_df = pd.read_csv(train_csv)
        self.train_df.columns = ['image1', 'image2', 'label']
        self.train_dir = train_dir
        self.transform = transform

    def __getitem__(self, index):
        image1_path = os.path.join(self.train_dir, self.train_df.iat[index, 0])
        image2_path = os.path.join(self.train_dir, self.train_df.iat[index, 1])
        img1 = Image.open(image1_path).convert("L")
        img2 = Image.open(image2_path).convert("L")

        if self.transform is not None:
            img1 = self.transform(img1)
            img2 = self.transform(img2)

        return img1, img2, torch.tensor([int(self.train_df.iat[index, 2])], dtype=torch.float32)

    def __len__(self):
        return len(self.train_df)

# Define the training function
def train(epochs, max_lr, model, train_dl, opt_func=torch.optim.SGD):
    torch.cuda.empty_cache()
    losses = []

    optimizer = opt_func(model.parameters(), lr=max_lr)
    sched = torch.optim.lr_scheduler.OneCycleLR(optimizer, max_lr, epochs=epochs,
                                                steps_per_epoch=len(train_dl))

    for epoch in range(1, epochs + 1):
        model.train()
        for batch_idx, (img0, img1, label) in enumerate(train_dl):
            img0, img1, label = img0.to(device), img1.to(device), label.to(device)
            optimizer.zero_grad()
            output1, output2 = model(img0, img1)
            loss_contrastive = criterion(output1, output2, label)
            loss_contrastive.backward()
            losses.append(loss_contrastive.item())
            optimizer.step()
        print(f'Cost at epoch {epoch} is {sum(losses)/len(losses)}')

    # Save the model after training
    torch.save(model.state_dict(), "siamese_model.pth")
    print("Model saved successfully!")

    return model

# Define data transformation
transform = transforms.Compose([
    transforms.Resize((100, 100)),
    transforms.ToTensor()
])

# Prepare data loaders (same as your existing code)
train_csv = "/content/drive/MyDrive/sign_data/train_data.csv"
train_dir = "/content/drive/MyDrive/sign_data/train"
train_ds = SiameseData(train_csv, train_dir, transform=transform)
train_dl = DataLoader(train_ds, shuffle=True, batch_size=32)

# Create and move the model to the device
model = SiameseNetwork().to(device)
criterion = ContrastiveLoss()

# Train the model
epochs = 5
max_lr = 0.01
opt_func = torch.optim.Adam

history = train(epochs, max_lr, model, train_dl, opt_func)

from google.colab import drive
drive.mount('/content/drive')



